/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface WaterIntakeInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addDailyIntake"
      | "getAverageIntake"
      | "getDayCount"
      | "getTotalIntake"
      | "protocolId"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "addDailyIntake",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAverageIntake",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getDayCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalIntake",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "protocolId",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "addDailyIntake",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAverageIntake",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDayCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalIntake",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "protocolId", data: BytesLike): Result;
}

export interface WaterIntake extends BaseContract {
  connect(runner?: ContractRunner | null): WaterIntake;
  waitForDeployment(): Promise<this>;

  interface: WaterIntakeInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addDailyIntake: TypedContractMethod<
    [intakeEuint32: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  getAverageIntake: TypedContractMethod<[], [string], "view">;

  getDayCount: TypedContractMethod<[], [string], "view">;

  getTotalIntake: TypedContractMethod<[], [string], "view">;

  protocolId: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addDailyIntake"
  ): TypedContractMethod<
    [intakeEuint32: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAverageIntake"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getDayCount"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getTotalIntake"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "protocolId"
  ): TypedContractMethod<[], [bigint], "view">;

  filters: {};
}
